### ISSUE TITLE
Add problem description in src/PROBLEMS.md 

### ISSUE THREAD

**Issue by codeIntrovert** [codeIntrovert/90daysOfDSA#1]
## Issue Title:
Add problem description in src/PROBLEMS.md

### Description:
The repository lacks problem descriptions in the `src/PROBLEMS.md` file beyond Day 15. This issue aims to enhance documentation by adding brief problem descriptions for Day 16 through Day 55 (or whatever is latest) in the same format as existing entries.

### Steps to Resolve:
1. Open the `/src` folder in the repository.
2. Locate and open `PROBLEMS.md`.
3. Review the existing format of problem descriptions for Day 15 or earlier entries.
4. Add brief problem descriptions for Day 16 through Day 55 (or latest) , maintaining the same format.
5. Ensure consistency in formatting and language.
6. Test by checking problems in folders of Day 16 till Day 55 (or latest) to confirm the accuracy of descriptions.

### Difficulty/Experience Level:
Beginner

### Labels:
- Good First Issue
- Documentation
- Java

**Comment by codeIntrovert** [comment]
+ Check programs in each folder of each day and write description in `PROBLEMS.MD ` as described above

**Comment by codeIntrovert** [comment]
@lokendarjangid

**Comment by lokendarjangid** [comment]
I am on it
